---
language: node_js
node_js: 8
sudo: required
dist: trusty

cache:
  yarn: true
  directories:
    - node_modules
env:
  matrix:
  - BROWSER=Chrome
addons:
  apt:
    packages:
    - google-chrome-stable
install:
  - yarn
script:
  - yarn run test
